
import __ASTRO_IMAGE_IMPORT_Z8jp1S from "/src/images/changelog/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fchangelog%2F1.md";
import __ASTRO_IMAGE_IMPORT_ZHfbke from "/src/images/changelog/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fchangelog%2F2.md";
import __ASTRO_IMAGE_IMPORT_Z1haWCz from "/src/images/changelog/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fchangelog%2F3.md";
import __ASTRO_IMAGE_IMPORT_Z1v7WuT from "/src/images/integrations/stripe.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F2.md";
import __ASTRO_IMAGE_IMPORT_27rxq3 from "/src/images/integrations/chargebee.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F1.md";
import __ASTRO_IMAGE_IMPORT_Z5Kcd from "/src/images/integrations/recurly.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F3.md";
import __ASTRO_IMAGE_IMPORT_2oTFc2 from "/src/images/integrations/xero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F5.md";
import __ASTRO_IMAGE_IMPORT_2lSfsn from "/src/images/integrations/sage.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F4.md";
import __ASTRO_IMAGE_IMPORT_Z1ORH9a from "/src/images/integrations/quickbooks.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F6.md";
import __ASTRO_IMAGE_IMPORT_1aovVP from "/src/images/blog/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md";
import __ASTRO_IMAGE_IMPORT_1SjmwC from "/src/images/blog/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md";
import __ASTRO_IMAGE_IMPORT_rtFm3 from "/src/images/blog/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md";
import __ASTRO_IMAGE_IMPORT_ZgqadJ from "/src/images/blog/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md";
import __ASTRO_IMAGE_IMPORT_ZYl0Nw from "/src/images/blog/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md";
import __ASTRO_IMAGE_IMPORT_Z1HfQoj from "/src/images/blog/6.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md";
export default new Map([["/src/images/changelog/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fchangelog%2F1.md", __ASTRO_IMAGE_IMPORT_Z8jp1S], ["/src/images/changelog/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fchangelog%2F2.md", __ASTRO_IMAGE_IMPORT_ZHfbke], ["/src/images/changelog/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fchangelog%2F3.md", __ASTRO_IMAGE_IMPORT_Z1haWCz], ["/src/images/integrations/stripe.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F2.md", __ASTRO_IMAGE_IMPORT_Z1v7WuT], ["/src/images/integrations/chargebee.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F1.md", __ASTRO_IMAGE_IMPORT_27rxq3], ["/src/images/integrations/recurly.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F3.md", __ASTRO_IMAGE_IMPORT_Z5Kcd], ["/src/images/integrations/xero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F5.md", __ASTRO_IMAGE_IMPORT_2oTFc2], ["/src/images/integrations/sage.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F4.md", __ASTRO_IMAGE_IMPORT_2lSfsn], ["/src/images/integrations/quickbooks.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F6.md", __ASTRO_IMAGE_IMPORT_Z1ORH9a], ["/src/images/blog/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md", __ASTRO_IMAGE_IMPORT_1aovVP], ["/src/images/blog/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md", __ASTRO_IMAGE_IMPORT_1SjmwC], ["/src/images/blog/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md", __ASTRO_IMAGE_IMPORT_rtFm3], ["/src/images/blog/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md", __ASTRO_IMAGE_IMPORT_ZgqadJ], ["/src/images/blog/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md", __ASTRO_IMAGE_IMPORT_ZYl0Nw], ["/src/images/blog/6.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md", __ASTRO_IMAGE_IMPORT_Z1HfQoj]]);
		